services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - todo-pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
